### ISSUE TITLE
Bot currently not working

### ISSUE THREAD

**Issue by chrischapman82** [leigholiver/replaybot#9] opened 2020-07-28 22:24 UTC
Hey. We've been using this bot on our server and it's been really useful. Didn't know how to reach out another way. It's currently not working.

**Comment by leigholiver** [comment] 2020-07-29 08:38
Hi, thanks for reporting it! I've done a quick test and it seems OK against my test replay, Are the replays from the new patch? I should have time this evening to take a proper look so I'll update you when I know more.

**Comment by chrischapman82** [comment] 2020-07-29 10:11
Hey. Yeah tried with 2 new patch replays and they both didn't display. Old patch replay displayed properly. A member mentioned that apparently breath (sc2replaystats dev) has to change a line of code every patch when parsing replays. Maybe that has something to do with it.

**Comment by leigholiver** [comment] 2020-07-29 10:16
Ah ok, yeah that's extremely likely to be the cause then. There is another open issue on the sc2reader repo for the same thing. As soon as there is an update their end I'll get it fixed.

**Comment by chrischapman82** [comment] 2020-07-29 10:38
awesome! thanks man for the quick support

**Comment by leigholiver** [comment] 2020-08-08 20:01
Fixed in #11

**Closed by leigholiver** 2020-08-08 20:01 UTC
